export const routesPath = {
  home: "/",
  signIn: "/signin",
  register: "/register",
  book: "books",
  category: "categories",
  dashBoard: "dashboard",
  user: "users",
  bookEdit: "books/:id/edit",
  bookCreate: "books/create",
  bookBorrowing: "books-borrowing",
  userProfile: "profile",
  emailConfirm: "/email-confirm",
  bookBorrowed: "/book-borrowed",
  bookDetail: "/books/:id/detail",
  forbidden: "/forbidden",
  reports: "reports",
};
